# run the same job on 2 CI machines in parallel
# https://docs.microsoft.com/en-us/vsts/pipelines/process/phases
phases:
- phase: Test
  queue: 'Hosted Linux Preview'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  # VSTS hosted Linux agents already have a LOT of dependencies preinstalled
  # https://github.com/Microsoft/vsts-agent-docker
  # so we don't have to install all recommended Cypress dependencies
  # https://on.cypress.io/continuous-integration#Dependencies
  - script: |
      apt-get update && apt-get install -y libgconf-2-4
    displayName: 'install dependencies'
  - script: |
      yarn install
    displayName: 'npm install and build'
  - script: |
      yarn cypress verify
    displayName: 'Cypress verify'
  - script: |
      yarn test
    displayName: 'Run Cypress tests'